# Generated by Django 5.1.4 on 2024-12-27 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0005_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-creation_date']},
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('body', models.TextField(verbose_name='Cuerpo')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='a_posts.comment')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
