# Generated by Django 5.1.4 on 2025-01-23 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0007_likedposts_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likedposts',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_user_post_like'),
        ),
    ]
