# Generated by Django 5.1.4 on 2025-01-23 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='lastmessage_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
